"""Custom training loop for FLAN-T5 + LoRA on the BioLaySumm dataset."""

from __future__ import annotations

import argparse
import json
import os
import random
import time
from contextlib import nullcontext
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import torch
from torch.optim import AdamW
from torch.utils.data import DataLoader, Subset
from tqdm import tqdm
import evaluate

from dataset import RadiologyDataset
from modules import ModelConfig, load_model_and_tokenizer, print_model_info

# ---------------------------------------------------------------------------
# Environment tweaks to quiet common backend warnings
# ---------------------------------------------------------------------------
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "3")
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # type: ignore

    HAS_MPL = True
except ImportError:  # pragma: no cover - optional dependency
    HAS_MPL = False
    plt = None  # type: ignore


rouge_metric = evaluate.load("rouge")


# ---------------------------------------------------------------------------
# Reproducibility / hardware helpers
# ---------------------------------------------------------------------------

def set_seed(seed: int) -> None:
    """Set RNG seeds for Python, NumPy, and PyTorch (CPU/GPU).

    Args:
        seed: Seed value applied across Python, NumPy, and PyTorch RNGs.
    """
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    mps_backend = getattr(torch.backends, "mps", None)
    if mps_backend and mps_backend.is_available():  # pragma: no cover - requires macOS
        from torch import mps

        mps.manual_seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    print(f"✅ Random seed set to {seed}")


def get_hardware_info() -> Dict[str, Optional[str]]:
    """Collect lightweight hardware diagnostics for logging.

    Returns:
        Mapping of hardware and runtime properties such as CUDA availability,
        GPU memory, and PyTorch version.
    """
    info: Dict[str, Optional[str]] = {
        "device": "cpu",
        "cuda_available": torch.cuda.is_available(),
        "cuda_version": torch.version.cuda if torch.cuda.is_available() else None,
        "pytorch_version": torch.__version__,
        "num_gpus": torch.cuda.device_count() if torch.cuda.is_available() else 0,
        "gpu_name": None,
        "gpu_vram_total_gb": None,
        "gpu_vram_available_gb": None,
        "gpu_compute_capability": None,
        "mps_available": bool(getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()),
    }

    if info["cuda_available"]:
        info["device"] = "cuda"
        try:
            props = torch.cuda.get_device_properties(0)
            info["gpu_name"] = torch.cuda.get_device_name(0)
            total_vram = props.total_memory / (1024**3)
            allocated = torch.cuda.memory_allocated(0) / (1024**3)
            info["gpu_vram_total_gb"] = f"{total_vram:.2f}"
            info["gpu_vram_available_gb"] = f"{(total_vram - allocated):.2f}"
            info["gpu_compute_capability"] = f"{props.major}.{props.minor}"
        except RuntimeError as err:  # pragma: no cover - defensive
            info["gpu_error"] = str(err)

    return info


def print_hardware_info(info: Dict[str, Optional[str]]) -> None:
    """Pretty-print hardware diagnostics.

    Args:
        info: Hardware metadata generated by :func:`get_hardware_info`.
    """
    print("\n" + "=" * 60)
    print("🖥️  Hardware Information")
    print("=" * 60)
    print(f"  PyTorch Version: {info['pytorch_version']}")
    print(f"  CUDA Available: {info['cuda_available']}")
    print(f"  MPS Available:  {info.get('mps_available', False)}")
    if info["cuda_available"]:
        print(f"  CUDA Version: {info['cuda_version']}")
        print(f"  GPU Name: {info['gpu_name']}")
        print(f"  Device Count: {info['num_gpus']}")
        if info["gpu_vram_total_gb"]:
            print(f"  VRAM Total: {info['gpu_vram_total_gb']} GB")
            print(f"  VRAM Available: {info['gpu_vram_available_gb']} GB")
        if info["gpu_compute_capability"]:
            print(f"  Compute Capability: {info['gpu_compute_capability']}")
    elif info.get("mps_available"):
        print("  Using Apple Silicon Metal Performance Shaders (MPS)")
    else:
        print("  Running on CPU")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def compute_rouge_metrics(
    predictions: List[np.ndarray],
    references: List[np.ndarray],
    tokenizer,
) -> Dict[str, float]:
    """Decode token IDs and compute aggregated ROUGE scores.

    Args:
        predictions: Token ID sequences generated by the model.
        references: Reference token ID sequences aligned with ``predictions``.
        tokenizer: Tokenizer used to decode token IDs into text.

    Returns:
        Aggregate ROUGE-1/ROUGE-2/ROUGE-L/ROUGE-Lsum scores keyed by metric.
    """
    decoded_preds = tokenizer.batch_decode(predictions, skip_special_tokens=True)
    decoded_refs = tokenizer.batch_decode(references, skip_special_tokens=True)

    # Add newlines to help ROUGE handle sentence boundaries.
    decoded_preds = [
        "\n".join(pred.strip().split(".")) if pred.strip() else "empty"
        for pred in decoded_preds
    ]
    decoded_refs = [
        "\n".join(ref.strip().split(".")) if ref.strip() else "empty"
        for ref in decoded_refs
    ]

    result = rouge_metric.compute(
        predictions=decoded_preds,
        references=decoded_refs,
        use_stemmer=True,
        use_aggregator=True,
    )

    return {
        "rouge1": float(result["rouge1"]),
        "rouge2": float(result["rouge2"]),
        "rougeL": float(result["rougeL"]),
        "rougeLsum": float(result["rougeLsum"]),
    }


# ---------------------------------------------------------------------------
# Manual trainer
# ---------------------------------------------------------------------------

class ManualTrainer:
    """Minimal, transparent training loop for seq2seq finetuning."""

    def __init__(
        self,
        model,
        tokenizer,
        train_loader: DataLoader,
        val_loader: DataLoader,
        device: torch.device,
        *,
        learning_rate: float = 3e-4,
        weight_decay: float = 0.01,
        output_dir: Path,
        use_mixed_precision: bool = True,
        gradient_accumulation_steps: int = 1,
        max_grad_norm: float = 1.0,
        save_steps: int = 0,
        eval_steps: int = 0,
        logging_steps: int = 50,
        max_target_length: int = 256,
        max_eval_batches: Optional[int] = None,
    ):
        """Initialise trainer state and optimiser configuration.

        Args:
            model: Seq2seq model to fine-tune.
            tokenizer: Tokenizer aligned with the ``model`` vocabulary.
            train_loader: Dataloader yielding training batches.
            val_loader: Dataloader yielding validation batches.
            device: Target compute device.
            learning_rate: Optimiser learning rate.
            weight_decay: Weight decay applied by AdamW.
            output_dir: Directory used to store checkpoints and logs.
            use_mixed_precision: Whether to enable AMP during training/eval.
            gradient_accumulation_steps: Number of mini-batches accumulated
                before each optimiser step.
            max_grad_norm: Gradient clipping threshold.
            save_steps: Step interval for non-best checkpoints (0 disables).
            eval_steps: Step interval for validation (0 disables).
            logging_steps: Step interval for progress bar updates.
            max_target_length: Maximum length used for generation during eval.
            max_eval_batches: Optional cap on validation batches processed.
        """
        self.model = model.to(device)
        self.tokenizer = tokenizer
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.device = device
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        self.gradient_accumulation_steps = max(1, gradient_accumulation_steps)
        self.max_grad_norm = max_grad_norm
        self.save_steps = max(0, save_steps)
        self.eval_steps = max(0, eval_steps)
        self.logging_steps = max(0, logging_steps)
        self.max_target_length = max_target_length
        self.max_eval_batches = max_eval_batches

        trainable_params = [p for p in self.model.parameters() if p.requires_grad]
        self.optimizer = AdamW(trainable_params, lr=learning_rate, weight_decay=weight_decay)

        self.use_mixed_precision = use_mixed_precision and device.type == "cuda"
        self.scaler = (
            torch.amp.GradScaler(device=device.type)
            if self.use_mixed_precision
            else None
        )

        self.global_step = 0
        self.best_val_loss = float("inf")
        self.best_rouge = 0.0
        self.train_losses: List[float] = []
        self.val_losses: List[float] = []
        self.rouge_scores: List[Dict[str, float]] = []

        print("\n" + "=" * 60)
        print("🎯 Trainer Initialised")
        print("=" * 60)
        print(f"  Device: {device}")
        print(f"  Mixed precision: {self.use_mixed_precision}")
        print(f"  Learning rate: {learning_rate}")
        print(f"  Weight decay: {weight_decay}")
        print(f"  Gradient accumulation: {self.gradient_accumulation_steps}")
        print(f"  Max grad norm: {self.max_grad_norm}")
        print(f"  Eval every N steps: {self.eval_steps or 'epoch'}")
        print(f"  Save every N steps: {self.save_steps or 'epoch'}")
        print(f"  Logging every N steps: {self.logging_steps}")
        print(f"  Output directory: {self.output_dir}")
        print("=" * 60 + "\n")

    # -----------------------------
    # Training / evaluation helpers
    # -----------------------------

    def train_epoch(self, epoch: int) -> float:
        """Run one full training epoch.

        Args:
            epoch: One-based epoch index for logging purposes.

        Returns:
            Average loss across the training dataloader for the epoch.
        """
        self.model.train()
        epoch_loss = 0.0
        progress = tqdm(self.train_loader, desc=f"Epoch {epoch}", leave=False)
        self.optimizer.zero_grad(set_to_none=True)

        accumulation_counter = 0
        for step, batch in enumerate(progress):
            loss_value = self._forward_backward(batch)
            epoch_loss += loss_value
            accumulation_counter += 1

            if accumulation_counter == self.gradient_accumulation_steps:
                self._optimizer_step()
                accumulation_counter = 0

                # Optional step-based evaluation / saving
                if self.eval_steps and self.global_step % self.eval_steps == 0:
                    val_loss, rouge = self.validate()
                    self.val_losses.append(val_loss)
                    self.rouge_scores.append(rouge)
                    if rouge["rougeLsum"] > self.best_rouge:
                        self.best_rouge = rouge["rougeLsum"]
                        self.save_checkpoint(epoch, val_loss, rouge, is_best=True)
                    self.model.train()

                if self.save_steps and self.global_step % self.save_steps == 0:
                    self.save_checkpoint(epoch, None, None, is_best=False)

            if self.logging_steps and (step + 1) % self.logging_steps == 0:
                progress.set_postfix(loss=f"{loss_value:.4f}", step=self.global_step)

        # Handle any leftover gradients
        if accumulation_counter > 0:
            self._optimizer_step()

        avg_loss = epoch_loss / len(self.train_loader)
        self.train_losses.append(avg_loss)
        return avg_loss

    def _forward_backward(self, batch: Dict[str, torch.Tensor]) -> float:
        """Perform a forward/backward pass on a single mini-batch.

        Args:
            batch: Tokenised batch containing ``input_ids``, ``attention_mask``,
                and ``labels`` tensors.

        Returns:
            Loss value (before gradient accumulation scaling) for logging.
        """
        input_ids = batch["input_ids"].to(self.device)
        attention_mask = batch["attention_mask"].to(self.device)
        labels = batch["labels"].to(self.device)

        autocast_ctx = (
            torch.amp.autocast(device_type=self.device.type)
            if self.use_mixed_precision
            else nullcontext()
        )
        with autocast_ctx:
            outputs = self.model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )
            loss = outputs.loss / self.gradient_accumulation_steps

        loss_value_tensor = loss.detach()
        loss_value = float(loss_value_tensor.item())
        if not torch.isfinite(loss_value_tensor):
            print("⚠️  Encountered non-finite loss; skipping backward step.")
            self.optimizer.zero_grad(set_to_none=True)
            if self.use_mixed_precision and self.scaler is not None:
                self.scaler.update()
            return loss_value

        if self.use_mixed_precision and self.scaler is not None:
            self.scaler.scale(loss).backward()
        else:
            loss.backward()

        return loss_value * self.gradient_accumulation_steps

    def _optimizer_step(self) -> None:
        """Apply accumulated gradients and advance the optimiser state."""
        if self.use_mixed_precision and self.scaler is not None:
            self.scaler.unscale_(self.optimizer)
        torch.nn.utils.clip_grad_norm_(self.model.parameters(), self.max_grad_norm)

        if self.use_mixed_precision and self.scaler is not None:
            self.scaler.step(self.optimizer)
            self.scaler.update()
        else:
            self.optimizer.step()

        self.optimizer.zero_grad(set_to_none=True)
        self.global_step += 1

    @torch.no_grad()
    def validate(self) -> (float, Dict[str, float]):
        """Evaluate the model on the validation loader.

        Returns:
            Tuple of (average validation loss, ROUGE score dictionary).
        """
        self.model.eval()
        total_loss = 0.0
        all_predictions: List[np.ndarray] = []
        all_references: List[np.ndarray] = []

        progress = tqdm(self.val_loader, desc="Validating", leave=False)
        for batch_idx, batch in enumerate(progress):
            input_ids = batch["input_ids"].to(self.device)
            attention_mask = batch["attention_mask"].to(self.device)
            labels = batch["labels"].to(self.device)

            autocast_ctx = (
                torch.amp.autocast(device_type=self.device.type)
                if self.use_mixed_precision
                else nullcontext()
            )
            with autocast_ctx:
                outputs = self.model(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    labels=labels,
                )
            total_loss += outputs.loss.item()

            generated = self.model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_length=self.max_target_length,
                num_beams=4,
                early_stopping=True,
            )

            all_predictions.extend(generated.cpu().numpy())
            labels_for_decode = labels.clone()
            labels_for_decode[labels_for_decode == -100] = self.tokenizer.pad_token_id
            all_references.extend(labels_for_decode.cpu().numpy())

            progress.set_postfix(loss=f"{outputs.loss.item():.4f}")

            if self.max_eval_batches and (batch_idx + 1) >= self.max_eval_batches:
                break

        denom = min(len(self.val_loader), batch_idx + 1) or 1
        avg_loss = total_loss / denom
        rouge = compute_rouge_metrics(all_predictions, all_references, self.tokenizer)
        return avg_loss, rouge

    def save_checkpoint(
        self,
        epoch: int,
        val_loss: Optional[float],
        rouge_scores: Optional[Dict[str, float]],
        *,
        is_best: bool,
    ) -> None:
        """Persist model adapters, tokenizer, and training state.

        Args:
            epoch: Epoch index associated with the checkpoint.
            val_loss: Validation loss recorded at save time.
            rouge_scores: Validation ROUGE metrics or ``None`` for step saves.
            is_best: Whether this checkpoint represents the best ROUGE so far.
        """
        target_dir = self.output_dir / ("best_model" if is_best else f"checkpoint-step-{self.global_step}")
        target_dir.mkdir(parents=True, exist_ok=True)

        self.model.save_pretrained(target_dir)
        self.tokenizer.save_pretrained(target_dir)

        state = {
            "epoch": epoch,
            "global_step": self.global_step,
            "val_loss": val_loss,
            "rouge_scores": rouge_scores,
            "best_rouge": self.best_rouge,
            "optimizer_state": self.optimizer.state_dict(),
            "scaler_state": self.scaler.state_dict() if self.scaler else None,
            "train_losses": self.train_losses,
            "val_losses": self.val_losses,
            "rouge_history": self.rouge_scores,
        }
        torch.save(state, target_dir / "training_state.pt")

        tag = "🌟 New best" if is_best else "💾 Saved"
        print(f"{tag} checkpoint → {target_dir}")

    # -----------------------------
    # Main entry point
    # -----------------------------

    def train(self, num_epochs: int) -> Dict[str, List[float]]:
        """Execute the full fine-tuning schedule.

        Args:
            num_epochs: Number of epochs to iterate over the training data.

        Returns:
            Dictionary containing loss histories, ROUGE history, best ROUGE,
            and total runtime in seconds.
        """
        print("\n" + "=" * 60)
        print("🚀 Starting fine-tuning")
        print("=" * 60)
        print(f"  Epochs: {num_epochs}")
        print(f"  Batches / epoch: {len(self.train_loader)}")
        total_steps = (
            num_epochs * len(self.train_loader) // self.gradient_accumulation_steps
        )
        print(f"  Total optimisation steps: {total_steps}")
        print("=" * 60 + "\n")

        start_time = time.time()

        for epoch in range(1, num_epochs + 1):
            epoch_start = time.time()
            train_loss = self.train_epoch(epoch)
            val_loss, rouge = self.validate()
            self.val_losses.append(val_loss)
            self.rouge_scores.append(rouge)

            if rouge["rougeLsum"] > self.best_rouge:
                self.best_rouge = rouge["rougeLsum"]
                self.save_checkpoint(epoch, val_loss, rouge, is_best=True)

            self.save_checkpoint(epoch, val_loss, rouge, is_best=False)

            elapsed = time.time() - epoch_start
            print("\n" + "-" * 60)
            print(f"Epoch {epoch} summary")
            print("-" * 60)
            print(f"  Train loss:   {train_loss:.4f}")
            print(f"  Val loss:     {val_loss:.4f}")
            print(f"  ROUGE-1:      {rouge['rouge1']:.4f}")
            print(f"  ROUGE-2:      {rouge['rouge2']:.4f}")
            print(f"  ROUGE-L:      {rouge['rougeL']:.4f}")
            print(f"  ROUGE-Lsum:   {rouge['rougeLsum']:.4f}")
            print(f"  Epoch time:   {elapsed:.2f}s")
            print("-" * 60 + "\n")

        total_time = time.time() - start_time
        print("\n" + "=" * 60)
        print("✅ Training complete")
        print("=" * 60)
        print(f"  Total time: {total_time / 60:.2f} minutes")
        print(f"  Best ROUGE-Lsum: {self.best_rouge:.4f}")
        print(f"  Final train loss: {self.train_losses[-1]:.4f}")
        print(f"  Final val loss:   {self.val_losses[-1]:.4f}")
        print("=" * 60 + "\n")

        return {
            "train_losses": self.train_losses,
            "val_losses": self.val_losses,
            "rouge_scores": self.rouge_scores,
            "best_rouge": self.best_rouge,
            "total_time": total_time,
        }


# ---------------------------------------------------------------------------
# Utilities for saving training summaries
# ---------------------------------------------------------------------------

def save_training_artifacts(
    output_dir: Path,
    args,
    hardware_info: Dict[str, Optional[str]],
    results: Dict[str, List[float]],
    model,
) -> None:
    """Persist JSON and text summaries mirroring the manual trainer.

    Args:
        output_dir: Directory where artefacts will be written.
        args: Parsed command-line arguments describing the run.
        hardware_info: Hardware metadata captured before training.
        results: Training results dictionary returned by :meth:`ManualTrainer.train`.
        model: Fine-tuned model used to gather parameter statistics.
    """
    output_dir.mkdir(parents=True, exist_ok=True)

    log_payload = {
        "hardware": hardware_info,
        "hyperparameters": {
            "model_name": args.model_name,
            "use_lora": args.use_lora,
            "lora_r": args.lora_r,
            "lora_alpha": args.lora_alpha,
            "lora_dropout": args.lora_dropout,
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "gradient_accumulation_steps": args.gradient_accumulation_steps,
            "learning_rate": args.learning_rate,
            "weight_decay": args.weight_decay,
            "max_grad_norm": args.max_grad_norm,
            "max_source_length": args.max_source_length,
            "max_target_length": args.max_target_length,
            "seed": args.seed,
        },
        "results": {
            "best_rouge_lsum": results["best_rouge"],
            "final_train_loss": results["train_losses"][-1],
            "final_val_loss": results["val_losses"][-1],
            "total_time_minutes": results["total_time"] / 60,
            "train_losses": results["train_losses"],
            "val_losses": results["val_losses"],
            "rouge_scores": results["rouge_scores"],
        },
        "timestamp": datetime.now().isoformat(),
    }

    json_path = output_dir / "training_log.json"
    with open(json_path, "w") as fh:
        json.dump(log_payload, fh, indent=2)

    report_path = output_dir / "training_report.txt"
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    pct = 100 * trainable_params / total_params if total_params else 0.0

    with open(report_path, "w") as fh:
        fh.write("=" * 80 + "\n")
        fh.write("FLAN-T5 LoRA Training Report\n")
        fh.write("=" * 80 + "\n\n")

        fh.write("Hardware Information\n")
        fh.write("-" * 80 + "\n")
        for key, value in hardware_info.items():
            fh.write(f"  {key}: {value}\n")

        fh.write("\nModel Configuration\n")
        fh.write("-" * 80 + "\n")
        fh.write(f"  Model: {args.model_name}\n")
        fh.write(f"  LoRA Enabled: {args.use_lora}\n")
        fh.write(f"  LoRA Rank: {args.lora_r}\n")
        fh.write(f"  LoRA Alpha: {args.lora_alpha}\n")
        fh.write(f"  LoRA Dropout: {args.lora_dropout}\n")
        fh.write(f"  Total Parameters: {total_params:,}\n")
        fh.write(f"  Trainable Parameters: {trainable_params:,}\n")
        fh.write(f"  Trainable %: {pct:.2f}%\n")

        fh.write("\nTraining Configuration\n")
        fh.write("-" * 80 + "\n")
        fh.write(f"  Epochs: {args.epochs}\n")
        fh.write(f"  Batch Size: {args.batch_size}\n")
        fh.write(f"  Gradient Accumulation Steps: {args.gradient_accumulation_steps}\n")
        fh.write(f"  Effective Batch Size: {args.batch_size * args.gradient_accumulation_steps}\n")
        fh.write(f"  Learning Rate: {args.learning_rate}\n")
        fh.write(f"  Weight Decay: {args.weight_decay}\n")
        fh.write(f"  Max Grad Norm: {args.max_grad_norm}\n")
        fh.write(f"  Max Source Length: {args.max_source_length}\n")
        fh.write(f"  Max Target Length: {args.max_target_length}\n")
        fh.write(f"  Mixed Precision: {not args.no_mixed_precision}\n")
        fh.write(f"  Random Seed: {args.seed}\n")

        fh.write("\nTraining Results\n")
        fh.write("-" * 80 + "\n")
        fh.write(f"  Total Time: {results['total_time'] / 60:.2f} minutes\n")
        fh.write(f"  Best ROUGE-Lsum: {results['best_rouge']:.4f}\n")
        fh.write(f"  Final Train Loss: {results['train_losses'][-1]:.4f}\n")
        fh.write(f"  Final Val Loss: {results['val_losses'][-1]:.4f}\n")
        if results["rouge_scores"]:
            final_rouge = results["rouge_scores"][-1]
            fh.write(f"  Final ROUGE-1: {final_rouge['rouge1']:.4f}\n")
            fh.write(f"  Final ROUGE-2: {final_rouge['rouge2']:.4f}\n")
            fh.write(f"  Final ROUGE-L: {final_rouge['rougeL']:.4f}\n")
            fh.write(f"  Final ROUGE-Lsum: {final_rouge['rougeLsum']:.4f}\n")

        fh.write("\nLoss History\n")
        fh.write("-" * 80 + "\n")
        for idx, (train_loss, val_loss) in enumerate(
            zip(results["train_losses"], results["val_losses"]), start=1
        ):
            fh.write(f"  Epoch {idx}: Train={train_loss:.4f}, Val={val_loss:.4f}\n")

        if results["rouge_scores"]:
            fh.write("\nROUGE History\n")
            fh.write("-" * 80 + "\n")
            for idx, score in enumerate(results["rouge_scores"], start=1):
                fh.write(f"  Checkpoint {idx}: {score}\n")

        fh.write("\nGenerated at: " + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "\n")
        fh.write("=" * 80 + "\n")

    print(f"📊 Training artefacts saved to {output_dir}")


def save_training_plots(output_dir: Path, results: Dict[str, Any]) -> None:
    """Persist loss and ROUGE curves for quick visual inspection."""
    if not HAS_MPL:
        print("⚠️  Matplotlib not available — skipping training plots.")
        return

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Loss curves
    loss_path = output_dir / "loss_curve.png"
    if results.get("train_losses"):
        epochs = range(1, len(results["train_losses"]) + 1)
        plt.figure(figsize=(8, 5))
        plt.plot(epochs, results["train_losses"], label="Train Loss", marker="o")
        if results.get("val_losses"):
            plt.plot(epochs, results["val_losses"], label="Validation Loss", marker="o")
        plt.xlabel("Epoch")
        plt.ylabel("Loss")
        plt.title("Training vs Validation Loss")
        plt.grid(True, linestyle="--", alpha=0.4)
        plt.legend()
        plt.tight_layout()
        plt.savefig(loss_path)
        plt.close()
        print(f"📉 Saved loss curve to {loss_path}")

    # ROUGE curves
    rouge_scores = results.get("rouge_scores") or []
    if rouge_scores:
        rouge_keys = sorted(rouge_scores[0].keys())
        rouge_path = output_dir / "rouge_curves.png"
        plt.figure(figsize=(8, 5))
        for key in rouge_keys:
            values = [score.get(key) for score in rouge_scores]
            plt.plot(range(1, len(values) + 1), values, label=key.upper(), marker="o")
        plt.xlabel("Evaluation Step")
        plt.ylabel("ROUGE Score")
        plt.title("ROUGE Metrics Over Time")
        plt.ylim(0, 1)
        plt.grid(True, linestyle="--", alpha=0.4)
        plt.legend()
        plt.tight_layout()
        plt.savefig(rouge_path)
        plt.close()
        print(f"📈 Saved ROUGE curves to {rouge_path}")


# ---------------------------------------------------------------------------
# Argument parsing & main entry
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for manual fine-tuning.

    Returns:
        Namespace containing all CLI options for the training script.
    """
    parser = argparse.ArgumentParser(
        description="Manual FLAN-T5 + LoRA training loop for BioLaySumm",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # Model / LoRA
    parser.add_argument("--model_name", default="google/flan-t5-base")
    parser.add_argument("--use_lora", action="store_true", default=True)
    parser.add_argument("--lora_r", type=int, default=16)
    parser.add_argument("--lora_alpha", type=int, default=32)
    parser.add_argument("--lora_dropout", type=float, default=0.1)

    # Data
    parser.add_argument(
        "--data_dir",
        default="recognition/fineTuneRadiology_48543200/data",
        help="Directory containing train.csv / val.csv",
    )
    parser.add_argument(
        "--max_input_len",
        dest="max_source_length",
        type=int,
        default=1024,
        help="Legacy alias for --max_source_length.",
    )
    parser.add_argument("--max_target_len", dest="max_target_length", type=int, default=256)
    parser.add_argument(
        "--eval_batch_size",
        type=int,
        default=None,
        help="Override evaluation batch size (defaults to training batch size).",
    )
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument(
        "--subset",
        type=int,
        default=None,
        help="Optional number of training samples for quick experiments.",
    )

    # Training hyperparameters
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--lr", dest="learning_rate", type=float, default=3e-4)
    parser.add_argument("--weight_decay", type=float, default=0.01)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=1)
    parser.add_argument("--max_grad_norm", type=float, default=1.0)
    parser.add_argument("--max_eval_batches", type=int, default=None)

    # Logging & checkpointing
    parser.add_argument("--output_dir", default="./outputs_flan_t5_lora")
    parser.add_argument("--logging_steps", type=int, default=50)
    parser.add_argument("--eval_steps", type=int, default=0)
    parser.add_argument("--save_steps", type=int, default=0)
    parser.add_argument(
        "--eval_epoch",
        action="store_true",
        help="Evaluate only at epoch boundaries (overrides --eval_steps).",
    )
    parser.add_argument(
        "--save_epoch",
        action="store_true",
        help="Save checkpoints only at epoch boundaries (overrides --save_steps).",
    )

    # Precision / reproducibility
    parser.add_argument("--fp16", action="store_true", help="Hint to use fp16 mixed precision.")
    parser.add_argument(
        "--no_mixed_precision",
        action="store_true",
        help="Disable mixed precision even when a GPU is available.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--dry_run", action="store_true", help="Quick smoke test mode.")

    return parser.parse_args()


def prepare_dataloaders(args, tokenizer, device: torch.device) -> (DataLoader, DataLoader):
    """Build train/validation dataloaders from CSV splits.

    Args:
        args: Parsed CLI arguments containing data and batching options.
        tokenizer: Tokenizer used to instantiate :class:`RadiologyDataset`.
        device: Target device to inform DataLoader options.

    Returns:
        Tuple of training and validation dataloaders ready for use.
    """
    data_dir = Path(args.data_dir)
    train_csv = data_dir / "train.csv"
    val_csv = data_dir / "val.csv"
    if not train_csv.exists() or not val_csv.exists():
        raise FileNotFoundError(
            f"Expected train.csv and val.csv in {data_dir}. "
            "Run data_setup.py to download the dataset."
        )

    train_dataset = RadiologyDataset(
        csv_path=str(train_csv),
        tokenizer=tokenizer,
        max_source_length=args.max_source_length,
        max_target_length=args.max_target_length,
    )
    val_dataset = RadiologyDataset(
        csv_path=str(val_csv),
        tokenizer=tokenizer,
        max_source_length=args.max_source_length,
        max_target_length=args.max_target_length,
        prefix=train_dataset.prefix,
    )

    if args.subset:
        subset_size = min(len(train_dataset), args.subset)
        val_subset = max(1, subset_size // 10)
        train_dataset = Subset(train_dataset, range(subset_size))
        val_dataset = Subset(val_dataset, range(val_subset))
        print(f"⚙️  Using subset: {subset_size} train samples / {val_subset} val samples")

    if args.dry_run:
        train_limit = min(len(train_dataset), 8)
        val_limit = min(len(val_dataset), 4)
        train_dataset = Subset(train_dataset, range(train_limit))
        val_dataset = Subset(val_dataset, range(val_limit))
        print("🧪 Dry-run mode: limiting to 8 train / 4 val samples")

    pin_memory = device.type == "cuda"
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )
    eval_batch_size = args.eval_batch_size or args.batch_size
    val_loader = DataLoader(
        val_dataset,
        batch_size=eval_batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )
    return train_loader, val_loader


def main():
    """Entry point coordinating configuration, training, and reporting."""
    args = parse_args()

    # Derived flags
    if args.eval_epoch:
        args.eval_steps = 0
    if args.save_epoch:
        args.save_steps = 0

    if args.dry_run:
        print("\n" + "=" * 60)
        print("🧪 DRY-RUN MODE")
        print("=" * 60)
        args.epochs = 1
        args.logging_steps = max(1, min(args.logging_steps, 5))
        args.eval_steps = 0
        args.save_steps = 0
        print("  Adjusted epochs/logging for a quick smoke test.\n")

    print("\n" + "=" * 60)
    print("⚙️  Training Configuration")
    print("=" * 60)
    print(f"Model: {args.model_name}")
    print(f"LoRA: r={args.lora_r}, alpha={args.lora_alpha}, dropout={args.lora_dropout}")
    print(f"Epochs: {args.epochs}")
    print(f"Batch size: {args.batch_size}")
    print(f"Gradient accumulation: {args.gradient_accumulation_steps}")
    print(f"Learning rate: {args.learning_rate}")
    print(f"Max sequence lengths: input={args.max_source_length}, target={args.max_target_length}")
    print("=" * 60 + "\n")

    set_seed(args.seed)
    hardware = get_hardware_info()
    print_hardware_info(hardware)

    def detect_device() -> torch.device:
        if torch.cuda.is_available():
            return torch.device("cuda")
        mps_backend = getattr(torch.backends, "mps", None)
        if mps_backend and mps_backend.is_available():  # pragma: no cover - requires macOS
            return torch.device("mps")
        return torch.device("cpu")

    device = detect_device()
    print(f"🖥️  Using {device.type.upper()} for training.")

    use_mixed_precision = not args.no_mixed_precision and (device.type == "cuda")
    if args.fp16 and device.type == "cuda":
        use_mixed_precision = True

    print("📚 Loading model + tokenizer...")
    cfg = ModelConfig(
        model_name=args.model_name,
        use_lora=args.use_lora,
        lora_r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
    )
    model, tokenizer, _ = load_model_and_tokenizer(cfg, move_to_device=False)
    print_model_info(model)

    print(f"\n📂 Building dataloaders from {args.data_dir}")
    train_loader, val_loader = prepare_dataloaders(args, tokenizer, device)

    trainer = ManualTrainer(
        model=model,
        tokenizer=tokenizer,
        train_loader=train_loader,
        val_loader=val_loader,
        device=device,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        output_dir=Path(args.output_dir),
        use_mixed_precision=use_mixed_precision,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        max_grad_norm=args.max_grad_norm,
        save_steps=args.save_steps,
        eval_steps=args.eval_steps,
        logging_steps=args.logging_steps,
        max_target_length=args.max_target_length,
        max_eval_batches=args.max_eval_batches,
    )

    results = trainer.train(num_epochs=args.epochs)
    save_training_artifacts(Path(args.output_dir), args, hardware, results, model)
    save_training_plots(Path(args.output_dir), results)

    print("\n✅ Training complete! Check the output directory for artefacts and checkpoints.")


if __name__ == "__main__":
    main()
